- engine/session.js
- package-lock.json
- package.json
- spec/engine/playhead_spec.js
The TestAssetManager here is a hybrid of ours and the OTTera version, whereby you need to pass null or some options in as the first parameter if you want to define non-default assets.
> Added slate functionality and tests

- README.md
- engine/session.js
- spec/engine/engine_spec.js
- spec/engine/interface_spec.js
This PR adds support for error handler in the interface between asset manager and channel engine
> Error handler in asset manager interface

- package-lock.json
- package.json
Incorporate new package versions for hls-vodtolive and node-m3u8
> Update library versions to latest release

- README.md
- engine/memcached_state_store.js
- engine/memory_state_store.js
- engine/redis_state_store.js
- engine/server.js
- engine/shared_state_store.js
- package-lock.json
- package.json
This PR resolves feature request #50
> Feature to support memcached as shared session store between nodes

- engine/playhead_state.js
- engine/session.js
- engine/session_state.js
For high availability the engine supports both Redis and Memcached as shared store. This PR intends to reduce the network footprint by caching large objects in memory for a while. The cache TTL can be defined when initiating the server.
> Optimize throughput to share store

- engine/memcached_state_store.js
- engine/redis_state_store.js
- engine/server.js
- engine/session.js
- engine/shared_state_store.js
This PR adds the functionality to be able to reset the shared data store
> Ability to reset shared data store

- engine/redis_state_store.js
- engine/server.js
- engine/session.js
- engine/session_state.js
- engine/util.js
> #62: reworked leadership handling

- engine/chaos_monkey.js
- engine/session.js
This PR intends to resolve issue #78 and #79
> fix: corner cases whith insertion of slates when next VOD fails to load

- engine/server.js
- engine/session.js
- package-lock.json
- package.json
This PR gives the possibility to add some extra seconds on the EXT-X-TARGETDURATION added to the generated manifest.
> feat: add option to add extra seconds to the EXT-X-TARGETDURATION

- engine/server.js
Feature added in v2 to support AWS MediaTailor's way of accessing source feed
> AWS MediaTailor support

- engine/session_live.js
PR fixes #139 
The default sleep/delay time is set to 1500ms. Once some live segments are stored in SessionLive then the sleep time will be set according to the duration of the final segment * 0.25, a roughly fast enough time to better catch the sync window, and slow enough not to retry far too often.
> Fix: use dynamic delay time on media manifest load fail

- engine/session_live.js
PR should help fix #149 
I moved live segment duration calculation to after `_loadAllMediaManifest(.)`,
and also do not skip time compensation when fetch at live source is
not synced. I also removed old code for targetNumSeg
> Fix: Better selection of live playhead tick interval time

- engine/session.js
- engine/session_live.js
PR cleans up the remaining desync issues created from the last PR. 
A simpler approach is used now when an m3u8 request comes in and the playheadState mseq values are not synced up yet.
Since there is no guarantee that at the time of the request, the vod cache and the current playheadState values are should be used together, we simply return the last generated m3u8 from store.
Now this m3u8 is for one specific bitrate, so in this edge-case, the client may experience a sudden bitrate change. But it should be fine as it should return the normal bitrate on the next increment. 
Might change this solution in the future if a better one is found. But until then, I think this will work.
PR also improves live switch sync up when Leader and Follower switched on different V2L mseq.
> Fix: M3U8 Request on Load nextvod and Eliminate desync during live switch edge case

- engine/session.js
- engine/stream_switcher.js
- engine/util.js
- server-livemix.js
PR resolves #161 
PR also includes some bug fixes.
> Feat: Preroll for Stream Switching

- engine/session.js
When loading the next vod, a Follower node could skip state=VOD_NEXT_INITIATING and therefore miss the chance to gain vod cache clearing privileges. This would result in the node being stuck on an older vod cache, serving the wrong manifest to clients.
Now, a check is added in the case: SessionState.VOD_PLAYING that will allow for vodcache clearing when it is appropriate. 
Also, a variable name was changed for clarity.
> Fix: Missed vod cache clearing issue

- engine/session.js
This PR fixes a small logic mistake on an if-statement, and also added vod cache clearing privileges when an error is caught, and when a follower node happens to find itself in the state=VOD_NEXT_INIT.
> Fix: clean up condition for mseq passthrough

- engine/session.js
- engine/session_live.js
- package-lock.json
- package.json
PR updates @eyevinn/hls-vodtolive to v2.0.1, and also includes some clean up and minor default value tweeks
> chore: new hls-vodtolive version

- README.md
- engine/server.js
- engine/session.js
> Feat: add option for setting diff compensation rate

- engine/session.js
- engine/session_live.js
- engine/stream_switcher.js
> Fix: bumper cue issue and more

- engine/server.ts
> feat: add options method path for m3u8 endpoints

- package-lock.json
- package.json
> dependencies: Lock Restify Version

- README.md
- engine/server.ts
- engine/session.js
- engine/session_state.js
- package-lock.json
- package.json
- server-demux.ts
PR to resolve #202, #203, and #204
> V4 release candidate

- engine/session.js
- package-lock.json
- package.json
- spec/engine/init_switching_spec.js
> feat: support for assets with BYTERANGE

- engine/server.ts
- engine/session.js
- server-multicodec.ts
- tsconfig.json
Example implementation to showcase a channel profile with Dolby Atmos
> feat: support multi audio codec

- engine/redis_state_store.js
Log the time it takes for reading and writing to Redis and writes `SLOWREDIS` in the log if the I/O takes longer than 1000ms.
> chore: log time for redis i/o

- engine/session_state.js
- package-lock.json
- package.json
PR resolves #240 
PR also bumps the version of `hls-vodtolive` to v2.3.4
> Fix: increment by 0 not working

- engine/session.js
- package-lock.json
- package.json
This PR intends to solve #178 by upgrading restify version that is supported by node v18
> fix: support for node v18

- engine/session.js
- package-lock.json
- package.json
- spec/engine/init_switching_spec.js
PR uses hls-vodtolive v 2.3.8 which improves video and audio position alignment.
> chore: add better position logs and use hls-vodtolive v 2.3.8

- engine/server.ts
- engine/session.js
- engine/util.js
- package-lock.json
- package.json
- server-demux.ts
- spec/engine/util_spec.js
This PR intends to resolve #246
> #246 audio gid with slash

- engine/session.js
- engine/session_state.js
- engine/util.js
- package-lock.json
- package.json
Bump hls-vodtolive version 2.3.12 and add on some more data on two log lines.
> chore: bump hls vodtolive and add to log lines

- engine/session.js
PR is to resolve #263 
In the new helper function `isOldVod()` , some padding time was added to the 'age' of the vod, since it is possible that the CE could drift and load next vod up to 10 seconds too early.
> fix: edge case where newLeader not initiating next vod

- package-lock.json
- package.json
PR fixes #286 by utilizing a fix in the new hls-vodtolive version 3.1.1
> bump: hls-vodtolive to v3.1.2

- engine/server.ts
> Fix: Missing Newlines in Dummy Webvtt Response

- engine/redis_state_store.js
If environment variable `REDIS_VERBOSE_LOG` is set it will output metrics for Redis operations to console log in a CloudWatch metric parse:able JSON format
> feat: enable io ops logging for Redis

- engine/server.ts
- engine/session_live.js
- engine/stream_switcher.js
- package-lock.json
- package.json
PR contains some more stabilization to the livemix+demux+highavail feature, with some extra improvements and flexibility to the endpoint routes
> Fix: bump hls-vodtolive, and Make More Stable in HA Mode

- README.md
- engine/server.ts
- engine/session.js
- engine/session_live.js
- engine/stream_switcher.js
- examples/demux.ts
- examples/livemix-demux.ts
- examples/livemix.ts
- package-lock.json
- package.json
PR includes:
- updated libs hls-truncate and hls-repeat
- updated example scripts for the demux and livemix+demux feature
- updated readme
> Fix: subs support in truncate and repeat
