Eyevinn/channel-engine

- engine/server.js
- server.js
This PR provides a health check endpoint per channel (or session) that responds with 200 OK or 503 if playhead is either idle or failing.
> Healthcheck endpoint per session/channel

- README.md
- engine/server.js
- engine/session.js
- engine/util.js
- spec/engine/util_spec.js
This PR adds support for a very simplistic and basic filtering of media playlists included in the master manifest. Currently supports to filter on video bandwidth and video height. To specify a filter provide the query parameter `filter` when loading the master manifest, e.g. `(type=="video"&&height>200)&&(type=="video"&&height<400)`. This needs to be URL encoded resulting in the following URL: `http://localhost:8000/live/master.m3u8?channel=1&filter=%28type%3D%3D%22video%22%26%26height%3E200%29%26%26%28type%3D%3D%22video%22%26%26height%3C400%29`
> Master manifest filtering

- engine/server.js
Simple change to allow channel-level overrides to fallback slate behavior
> Allow custom slate per channel instead of engine-wide

- engine/memcached_state_store.js
- engine/redis_state_store.js
- engine/session_state.js
This PR resolves the bug where a second instance of the engine would wipe the shared store with init data on startup
> fix: shared store was initiated on startup

- engine/memcached_state_store.js
- engine/redis_state_store.js
- engine/server.js
- package-lock.json
- package.json
Add `X-Instance-Id` header in responses to identify server instance. This is useful when debugging HA setups.
> Generate instance id and include in header responses

- engine/memcached_state_store.js
- engine/memory_state_store.js
- engine/redis_state_store.js
- engine/server.js
- engine/session.js
- engine/session_state.js
- engine/shared_state_store.js
This PR resolves the issue where multiple nodes were incrementing the media sequences at the same time.
To make sure that only one node is incrementing the media sequence state we set a volatile key (a key that expires) in the shared session store that indicates which instance is the "incrementer". This key is volatile which means that if the current incrementer would crash the next one (first come - first served) will take over that role if that key is missing (has expired).
This PR also includes that the next vod response from the asset manager is also stored in shared store.
> High-avail fix: Media sequence incremented by multiple nodes

- engine/server.js
When endpoint `_handleMediaManifest` gets a request from a client, it is to wait for the stream switcher's verdict on the specific channel/session. Basically, shall the endpoint return an m3u8 from Session or SessionLive? (switcher returns true or false)
If the stream switcher is ever busy (preparing a switch between Session & SessionLive), the endpoint will wait for the completion. We do not want to return any manifest in this situation since the playheads do not wait for the switcher, and might return a manifest it shouldn't. 
If the switching is slow or fails, it will try again. If too much time passes then the request will cancel (timeout I believe).
However, there is a bug where the stream switcher instantly returns the value '**undefined**'. 
The absolute cause is atm unknown, a …
> Fix for bug where stream switcher returns undefined

- engine/server.js
This PR resolves #100 by adding an additional playback endpoint `/channels/:channelId/master.m3u8` that is equal to `/live/master.m3u8?channel=:channelId`
> feat: add an additional playback endpoint

- engine/session_live.js
- package-lock.json
- package.json
- server.js
Fix: #99 
This PR adds support for cue tags when transitioning from V2L->Live. 
If an `EXT-X-CUE-OUT` (with a duration) is included in the VOD manifest it will be preserved in the transition manifest.
> preserve ad markers when transition from V2L->Live

- engine/server.js
- engine/session_live.js
This PR fixes a bug where if a channel that didn't exist was trying to be reached the `stopPlayheadAsync()` would be called on a nonexistent live session which would cause the Channel Engine to crash. 
Also fixes a typo in Session Live related to ad markers.
> check if live session for current channel is available before stopping live playhead

- engine/session_live.js
Fixes: #103 
This PR fixes the playback issues in safari and adds support for `#EXT-X-DATERANGE` tags in live content. 
The playback issues was because the `#EXT-X-TARGETDURATION` could be set to a float.
> fix playback issues for live content in safari and add support for daterange tags

- engine/server.js
- engine/session.js
For #115 
This PR adds 3 new functions, they can be used to return all types of manifest that the channel engine can serve to a client.
It is a bit tedious to test (run in demux mode and try with different vods with a variety of audio groups and languages). 
I believe I have tested all basic cases and it works.
Specs for these can be written later I suppose
Example engine.getMasterManifest(chId) return string:
```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-STREAM-INF:BANDWIDTH=6134000,RESOLUTION=1024x458,CODECS="avc1.4d001f,mp4a.40.2"
master6134000.m3u8;session=1
```
Example engine.getMediaManifests(chId) return object:
```
{
1313000: "#EXTM3U . . .",
1212000: "#EXTM3U . . .",
789000: "#EXTM3U . . ."
}
```
Example engine.getAudioManifests(chId) return object:
```
{
'group-A': {
'lang-A': "EXTM3U . . …
```
> chore: added 3 new get functions in server.js

- README.md
This PR updates the readme to add that the `getSchedule(channelId)` should return a promise.
> Update `getSchedule(channelId)` section in readme

- engine/session.js
This PR addresses an issues caused by a race condition. There is a case where the leader and follower are out-of-sync and that is when the follower node "jumps over" vodMediaSeq 0 and goes directly to 1. Then it will not invalidate the currentVod cache and will be using the old one instead of the new one replaced by the leader.
> Fix race condition causing leader and follower node to be out of sync

- engine/session_live.js
PR fixes #138 
By not updating `lastRequestedMediaSeqRaw` when pushAmount is negative, the issue of appending duplicate segments is avoided.
> Fix: do not update prev mseq if pushAmount is negative

- engine/session.js
- engine/session_live.js
PR completes the fix for an edge-case where the client may request a manifest right before playheadState media seq values are updated but right after a new currentVod is set, and the currentVod cache has been cleared. Resulting in returning an unexpected manifest. This is a temporary issue as the cache and playheadState values will eventually be correct, but it is still not a desired outcome to have the channel-engine return any bad manifest.
We could just NOT clear the cache, and ensure that the outdated playheadState values match the cached currentVod...
...but the main reason for clearing the cache sooner than before was to handle _another_ edge case where the media sequence from a follower nodes perspective goes from ex, 14/15 -> 1/20, where media sequence 0 was essentially skipped. …
> fix: replace all relavant playheadState values

- engine/session.js
- engine/session_live.js
This PR will rework some changes made in the last PR.
- A Leader-node MUST skip playhead tick time compensation. While a Follower should skip the time compensation.
- The setting playheadState values to the newest sessionState values assumed that the sessionsState values were all actually already updated, but that is not always the case. Some might be updated at the time of the request but not necessarily all. 
So changing it back to how it was before.  Only this time, a Follower node will be sure to clear the vod cache as soon as its playheadState mseq is 0 or 1. 
That way, hopefully, when the client requests a manifest, the function `getCurrentMediaManifestAsync(.)` should no longer be creating a faulty Media Sequence count in the generated manifest.
> Fix: Rework previous issue fix

- README.md
- engine/util.js
- spec/engine/util_spec.js
PR to resolve #45 
The main issue seems to stem from the fact that the query string value needs ampersands (&&). 
I suggest would be to change the requirement for the '&&' chars and replacing it with 'AND'. 
This will yield more consistent query parsing in the restify server. 
I also went ahead and extended the `applyFilter(.)` utility function, so that it handles unsupported query formats,
and allows for also only setting a lower or upper condition boundary, as well as combining two types of conditions.
> Fix: Remove the need for ampersands in manifest filter query 

- engine/session.js
To avoid the edge-case where Leader updates currentVod too early.
For this condition to work properly 
```javascript
if (playheadState.vodMediaSeqVideo > sessionState.vodMediaSeqVideo) {
debug(`[${this._sessionId}]: Recently Loaded Next Vod. PlayheadState not up-to-date. Return the last generated m3u8`);
const m3u8 = await this._playheadState.getLastM3u8();
if (m3u8) {
return m3u8;
} else {
debug(`[${this._sessionId}]: We don't have any previously generated m3u8`);
}
}
```
`sessionState.vodMediaSeqVideo` would need to be set before the new currentVod in `_tickAsync()`. Otherwise the code block above would be skipped and leader would generate a manifest with an old `playheadState.vodMediaSeqVideo` value on a new currentVod
> chore: add original order of setting sessionState data

- engine/server.js
- engine/session.js
- engine/session_live.js
- engine/util.js
This PR cleans up redundant vod cache clearing checks. In earlier fixes, these cache clearers were needed to solve an issue.
However,  since we refactored the switchback-to-v2l logic a bit, these extra cache clearers became unnecessary.
I also added some boolean checks to have it so that the vod cache is only cleared once per case. 
eg. in the manifest request function `getCurrentMediaManifestAsync()`, if the current mseq=0|1 we would always clear the cache.
This would mean that the cache would be clear as often as manifest requests for that specific manifest sequence. There would be a window of ~(2*SegDuration) seconds, where we keep reading the vod from redis.
> Fix: Optimize vod cache clearing

- engine/server.js
- engine/session.js
- engine/session_live.js
- package-lock.json
- package.json
- server.js
- spec/engine/init_switching_spec.js
This PR adds a new version on `@eyevinn/hls-vodtolive`, which allows for setting the option for creating V2L media sequences that will always contain a new segment compared with the preceding media sequence.
To use the option, one will need to add `alwaysNewSegments: true` in the engine options json.
> NOTE: channel engine will still function as before even if an older version of hls-vodtolive is being used.
PR also includes some improvements to the vod cache clearing logic and other minor bug fixes.
Furthermore, when switching back to V2L from LIVE, the target-mseq to reload/splice live-segments in front of has changed to the mseq after the current, which is more approptiate.
> Feat: Add option for V2L mseqs to always contain new segments

- engine/session.js
- engine/session_live.js
- engine/stream_switcher.js
- package-lock.json
- package.json
- spec/engine/init_switching_spec.js
PR fixes a schedule alignment issue, with an updated version of hls-vodotolive
When setting `alwaysNewSegments` to true in engineOptions. the number of media sequences for an HLSVod is fewer than if it was set to false. This is because we may in some sequences eject 2 or more top segments to make room for one larger segment. Thus creating 1 sequence instead of 2.
>Normally, when a new segment is too large to append, it is skipped and added to the next sequence instead.
And with fewer sequences, we get fewer playhead ticks for a VOD, e.i. 
if CE consumes the msequences at a constant pace then it will finish earlier in comparrison, thus loading the next vod too early, when using `alwaysNewSegments`.  The time difference between when a VOD is finished compared to its schedule end_time will …
> Fix: Session Playhead moving too quickly when 'alwaysNewSegments' is set

- engine/stream_switcher.js
- package-lock.json
- package.json
PR makes a quick fix to a minor issue.
The previous cue tag bumper issue, where it is to always add a cue in tag segment item in front of the bumper segments, missed to properly handle the case where the last segment is a solo discontinuity tag. 
Before, the function `_mergeSegments()`  (in stream_switcher.js) would add no extra segment items/tags if the V2L segments already had a tag as the last segment item. However, unless the last segment item has a cue in-tag, then it is needed to be added.
PR also updates the version from 3.3.4 to 3.3.5
> Fix: cue tag still not before bumper

- engine/session.js
- engine/session_live.js
TLDR; Check if store segments are old based on segment data rather than leader mseq value.
There is a small risk where the Leader node is writing to store while Follower node is reading from store in a Session Live increment, resulting in the Follower reading a new leaderMseqRaw value but an old liveSegsForFollowers values in store.
Follower node should, wait and retry reading from the store if the values in store happen to be something it has already collected in the previous increment.
> fix: better check for old segments in store

- engine/session.js
PR resolves #184 
Summary: The problem was that if maxTickInterval was set below the segment length it would cause safari to become out of sync and the player would stop requesting new manifests.
> BUG: Playhead Tick Compensation Logic Blocked By Low MaxTickInterval

- .github/workflows/publish.yml
- .gitignore
- engine/server.ts
- engine/util.js
- index.js
- index.ts
- package-lock.json
- package.json
- server-demux.ts
- server-livemix.ts
- server.ts
- spec/engine/engine_spec.js
- spec/engine/interface_spec.js
- tsconfig.json
This PR provides typescript types for external interfaces and classes. Porting the entire project to typescript is not part of this PR. Breaking change is related to default export and the following has changed:
```
const ChannelEngine = require("eyevinn-channel-engine");
```
is changed to:
```
const { ChannelEngine } = require("eyevinn-channel-engine");
```
Documentation site will be updated with this change.
> feat: Typescript types

- engine/server.ts
PR resolves #192 
Added new type definitions for closed-captions object.
Support for closed-captions has been added and is currently in the ChannelEngine.
To enable closed-captions on a channel. Specify the closed-captions config in the ChannelManager, e.g. 
```js
class RefChannelManager implements IChannelManager {
getChannels(): Channel[] {
return [{ id: "1", profile: this._getProfile(), closedCaptions: this._getClosedCaptions() }];
}
_getProfile(): ChannelProfile[] {
return [
{ bw: 6134000, codecs: "avc1.4d001f,mp4a.40.2", resolution: [1024, 458] },
{ bw: 2323000, codecs: "avc1.4d001f,mp4a.40.2", resolution: [640, 286] },
{ bw: 1313000, codecs: "avc1.4d001f,mp4a.40.2", resolution: [480, 214] },
];
}
_getClosedCaptions(): ClosedCaptions[] {
return [
{ lang: "eng", name: "english", auto: …
```
> feat: add type definition for closed captions

- engine/session.js
- server-demux.ts
To render audio streams in the index manifest should not be needed as the URIs are defined in the audio rendition
> fix: do not render audio stream in index manifest

- engine/session.js
Two contributors were identified with causing buffer to the stream when running CE in HA mode.
- Audio Manifest endpoint fn does not clear vod cache independently from the video manifest endpoint. CE could return faulty audio manifest.
- When the leader node is loading the next vod and a m3u8 is requested, earlier CE would return the lastM3u8, however this m3u8 file is not shared between nodes and is not necessarily the most recent m3u8 the CE node sent. Instead of returning an old m3u8, it gave better results to simply wait for 1s and provide the leader node time to finish loading the next vod and updating the data in store.
> fix: Buffer Stalling Issues in HA

- engine/server.ts
This PR adds `Cache-Control: max-age=300` to master manifest response
> fix: master manifests should be cached

- engine/session.js
- package-lock.json
- package.json
PR does some fixes and improvements.
The idea of 'fast-forwarding' the audio mseq to match the playhead position of the video mseq, seems to have been implemented in the wrong place in the engine flow.
Surprisingly, the streams were still playable (enough in sync). But it may cause possible buffer stalls I believe.  
In a nutshell, first we compare current position in the video mseq vs audio mseq. If the audio mseq is behind then we check the position of the next audio mseq and compare again.
The issue is, when we do find the correct audio mseq, we do not act until the next tick. The positions should really be paired on the same tick. 
Before:
```
2023-03-08T08:05:50.095Z engine-session [1]: INCREMENT (mseq=107) vodMediaSeq=(3_5 of 13_25)  // Just incremented and current sequences are 3 …
```
> Fix: More CE V4 Stablization in HA-mode DRAFT

- engine/server.ts
- engine/session.js
- engine/util.js
- package-lock.json
- package.json
- server-demux.ts
- server-multicodec.ts
This PR addresses the issue where the correct audio playlist was not always chosen when working with demuxed and VODs with multiple audio codecs. This fix assumes though that a combination of audioGroupId and Channels can be mapped to an audio playlist.
> fix: correct audio group was not always chosen

- engine/redis_state_store.js
- engine/server.ts
- engine/session.js
This adds the option to configure the Volatile Key TTL that is used by Redis shared store for the leader key for example
> fix: option to override default volatile key TTL

- engine/session.js
This PR fixes the issue when a chosen audioGroupId for a stream is not available in the current VOD's list of audio group Ids. In that case use a fallback
> fix: wrong audio group Id sometimes selected for a stream

- engine/server.ts
- engine/session.js
This PR adds an option to the channel profile audio track to override audio manifest filename for a specific language.
> fix: profile option to override audio manifest filename for a language

- engine/session.js
PR fixes a faulty if statement that allowed for unnecessary when the video playhead and audio playhead positions are perfectly aligned.
> fix: when playhead pos diff is 0 step mseq equally

- engine/server.ts
- engine/session.js
- package-lock.json
- package.json
- spec/engine/init_switching_spec.js
This PR addresses #243 and adds PDT on each segment given that the vod-response from the asset manager contains wall-clock time of the VOD start time as a unix timestamp.
```
export interface VodResponse {
...
// Wall-clock start time of the VOD as unix ts. If set
// the program-date-time will be added to each segment
unixTs?: number;
}
```
> fix: insert PDT on each segment

- package-lock.json
- package.json
Handle VOD with BYTERANGE that are not providing offset on each segment. Normalizes the source VOD by calculating and adding the offset on each segment in those cases where it is missing.
> fix: handle VOD without byterange offsets

- server-drm.ts
- tsconfig.json
This PR intends to resolve #224
> feat: support for DRM encrypted VODs

- .gitignore
- engine/playhead_state.js
- engine/server.ts
- engine/session.js
- engine/session_live.js
- engine/session_state.js
- engine/subtitle_slicer.js
- index.ts
- package-lock.json
- package.json
- server-demux.ts
- spec/engine/subtitle_spec.js
- spec/testvectors/subtitle_file.webvtt
- spec/testvectors/subtitle_file_2.webvtt
Before the work was done in this PR, we did not have any support for subtitles in Channel engine. This pr will solve that by implementing support for WebVTT subtitles.
The work that has been done is to implement the communication between CE and hls-Vod2Live for subtitles, implement endpoints for getting subtitle manifest, handle splicing WebVtt files to match video segment length, and supply empty/dummy WebVtt files.
This PR aims to solve issue https://github.com/Eyevinn/channel-engine/issues/44
> Feat subtitle support

- engine/server.ts
no need to use a channel specific endpoint url for these functions
> fix: changed endpoint for vtt dummy and slice endpoint

- engine/server.ts
- engine/stream_switcher.js
If a timedMetadata object is included in the schedule a daterange tag with this metadata will be inserted when the preroll is inserted.
> feat: insert daterange metadata on live-switching

- engine/server.ts
- engine/session.js
If a `desiredDuration` is included in the VOD response from the adapter the engine will truncate the VOD to be as close as possible as requested.
> feat: truncate VOD if requested

- engine/session_state.js
When resetting the store, the title for a leader is up for grabs, and a new leader can be crowned.
However, the new follower (in this case ex-leader) node could still have its own instanceId in its leader cache for a couple more seconds.
If the CE is ever in this state right before loading a vod, then the follower node could set the currentVod, and store it in the local cache. Even if it a few seconds later corrects itself and realizes that it is NOT the leader, it still has the 'wrong' currentVod in the local cache and will not clear it, while the 'real' currentVod is available in the store (set there by the leader).
The result will be that the nodes are desynced, i.e. The nodes are serving manifests from different vods.
This PR attempts to solve this, by ensuring that only real leaders …
> fix: Ensure CurrentVod Is Only Ever Set By Leader

- engine/session_state.js
Even though a follower node is never supposed to set vods in storage, there are a few cases where it can happen. Where a follower node might find itself in a state where it thinks it is allowed to set the currentVod, it needs to be fed the actual currentVod when attempting. 
Right now when it tries `setCurrentVod(..)` does not do this.
> Handle Case Where Follower-Node Does Not Get The CurrentVod

- engine/server.ts
Setting the engine option `dummySubtittleEndpoint` decides what URI each dummy subtitle segment should have. The thought is that this URL should point to an empty webvtt file located somewhere on the public internet. 
However, when setting a string that is an absolute URL, the engine bugs and breaks.
This PR will resolve that issue.
> fix: decouple restify path and endpoint config dependency

- engine/session.js
For a demuxed stream, the CE tries to keep the video and audio streams aligned as best as possible.
It does this by comparing each track's playhead position value for a particular mseq.
If the difference is significant enough then it will increment the audio track faster than video.
If this happens, the audio track should also be able to skip an increment to allow for the video stream to catch up.   
However, when comparing current playhead positions, the difference could be really small. i.e. 0.0000002 
Due to what could be Javascript floating point error. So in a case where the diff should have equated to Zero, but didn't, the wrong behavior gets triggered. Resulting in the audio track not allowing the video track to catch up when it should have. 
i.e. The Audio track is constantly 1 …
> fix: Increase Audio Increment Limit

- engine/session.js
For a demuxed stream, the CE tries to keep the video and audio streams aligned as best as possible.
It does this by comparing each track's playhead position value for a particular mseq.
If the difference is significant enough then it will increment the audio track faster than video.
If this happens, the audio track should also be able to skip an increment to allow for the video stream to catch up.   
However, when comparing current playhead positions, the difference could be really small. i.e. 0.0000002 
Due to what could be Javascript floating point error. So in a case where the diff should have equated to Zero, but didn't, the wrong behavior gets triggered. Resulting in the audio track not allowing the video track to catch up when it should have. 
i.e. The Audio track is constantly 1 …
> fix: audioIncrement stepping when it should not due to float point error

- engine/session.js
PR is a revised fix for the previous issue of 
```
For a demuxed stream, the CE tries to keep the video and audio streams aligned as best as possible.
It does this by comparing each track's playhead position value for a particular mseq.
If the difference is significant enough then it will increment the audio track faster than video.
If this happens, the audio track should also be able to skip an increment to allow for the video stream to catch up.
However, when comparing current playhead positions, the difference could be really small. i.e. 0.0000002
Due to what could be Javascript floating point error. So in a case where the diff should have equated to Zero, but didn't, the wrong behavior gets triggered. Resulting in the audio track not allowing the video track to catch up when it should …
```
> fix: audio increment calculation stepping when it should not V3

- engine/session.js
Consider the case where a leader node dies when trying to setCurrentVod in store. Since this is one of the last values written to store in a VOD_NEXT_INIT state, all other values like **vodMediaSeq** and **mediaSeq** are already updated at that point.
So when the follower node becomes the new leader node, it is to take over and perform the VOD_NEXT_INIT state itself. But it does not know if the **mediaSeq** value for example is from the new vod or the prev vod. It cannot make that distinction. What happens is that it loads the vod and stores a new mediaSeq as (old mediaSeq + old final-vodMediaSeq). But the issue here is that it is using the new mediaSeq value that the prev leader put in. 
This results in the leader node creating a mediaSeq that is too large and the stream will have jumped …
> fix: New Leader Risk Using Values Set By Prev Leader

- engine/server.ts
- engine/session.js
- engine/session_state.js
- package-lock.json
- package.json
This PR bumps hls-vodtolive version to 4.0.0 and supports the handling of the new option in it, by introducing a new engineOption `partialStoreHLSVod`
> Feat: add option for partially storing HLSVod Json

- engine/memcached_state_store.js
- engine/memory_state_store.js
- engine/redis_state_store.js
- engine/server.ts
- engine/session.js
- engine/shared_state_store.js
This PR resolves #285 
Also added a new option `sessionResetKey`.
When set, the `/reset` and `/reset/:id` endpoints will start to require a matching API key in the request query in order to perform a reset.
eg, 
```
https://vc.engine.host.com/reset?key=<sessionResetKey>
```
> Feat: Add Reset by Channel feature

- engine/server.ts
- engine/session.js
PR resolves #297 by introducing a new engine option `sessionEventStream: boolean` 
Enabling this option, indicates that you plan on polling the CE for a stream of session specific events.
> Fix: Disable Eventstream by Default

- engine/preflight.js
- engine/server.ts
- examples/default.ts
If engine option `sessionHealthKey` is set it is mandated to provide the header 'x-health-key' in the GET request on the aggreggated session health endpoint
> feat: option to protect session health endpoint with a key

- engine/session.js
- package-lock.json
- package.json
- spec/engine/session_spec.js
The Playhead speed for the different tracks in the CE is different for video tracks and audio tracks. However, subtitle tracks were initially assumed to always have segments of durations equal to their video segment counterparts, so the playhead speed for subtitle tracks would just follow the one for video. This does not work that well if the subtitle track segments are different from video track segments. The media sequence for subtitles would lag behind. Subtitle segments would get out of sync with video.
This PR solves this issue by using an updated version of `@eyevinn/hls-vodtolive` where the "deltaTimesSubtitle" list now contains more accurate values. Making it possible for subtitle tracks to have an independent playhead speed. The media sequence for subtitles should now …
> Fix: Subtitle Track Playhead is dependant Of Video Track

- engine/session.js
- package-lock.json
- package.json
With this bump to the `@eyevinn/hls-vodtolive` lib, this PR can have CE accommodate the feature requested in #208.
NOTE - For this to work you will need:
- to couple CE with the `@eyevinn/lambda-stitch` ^v0.2.4 when serving vod URLs to the engine. 
- to enable PDT timestamps. You can do so by letting the assetManager adapter insert a UNIX timestamp in the field `unixTs` of the returned vod item in the response for assetManager function `getNextVod()`
> chore: update hls-vodtolive to version 4.1.3

- engine/server.ts
- engine/session.js
- package-lock.json
- package.json
This PR will make use of Fastify instead of Restify as Restify is old and is not maintained anymore. 
However, if we use a Fastify version higher than 3.x then it will introduce a breaking change as the CE will no longer support node v14.
> replace restify lib with fastify lib
